param(
    [string]$Part1Manifest = "./configs/wallets-manifest.challenge3-part1.json",
    [string]$Part2Manifest = "./configs/wallets-manifest.challenge3-part2.json",
    [string]$Part1WalletsDir = "./wallets/challenge3-part1",
    [string]$Part2WalletsDir = "./wallets/challenge3-part2",
    [int]$TargetShard0 = 166,
    [int]$TargetShard1 = 167,
    [int]$TargetShard2 = 167
)

go run ./cmd/genwallets `
    -mode challenge3 `
    -manifest $Part1Manifest `
    -wallets-dir $Part1WalletsDir `
    -prefix c3p1 `
    -target-shard0 $TargetShard0 `
    -target-shard1 $TargetShard1 `
    -target-shard2-c3 $TargetShard2 `
    -status challenge3_part1_sender `
    -extra-tags sender,challenge3,part1 `
    -notes "Generated by run-gen-challenge3-wallets.ps1 for Challenge 3 Part 1."

if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

go run ./cmd/genwallets `
    -mode challenge3 `
    -manifest $Part2Manifest `
    -wallets-dir $Part2WalletsDir `
    -prefix c3p2 `
    -target-shard0 $TargetShard0 `
    -target-shard1 $TargetShard1 `
    -target-shard2-c3 $TargetShard2 `
    -status challenge3_part2_sender `
    -extra-tags sender,challenge3,part2 `
    -notes "Generated by run-gen-challenge3-wallets.ps1 for Challenge 3 Part 2."

exit $LASTEXITCODE
