package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"encoding/pem"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"kwakbon/internal/manifest"
	"kwakbon/internal/wallets"
)

func main() {
	var (
		manifestPath = flag.String("manifest", "./configs/wallets-manifest.json", "Path to wallets manifest JSON")
		walletsDir   = flag.String("wallets-dir", "./wallets", "Directory where PEM files are written")
		targetTotal  = flag.Int("target-total", 497, "Target total wallet count in manifest after generation")
		targetShard2 = flag.Int("target-shard2", 250, "Target shard-2 wallet count in manifest after generation")
		activeShard2 = flag.Int("active-shard2", 150, "How many shard-2 wallets should be marked active_candidate")
		reserveShard2 = flag.Int("reserve-shard2", 100, "How many shard-2 wallets should be marked warm_reserve")
		prefix       = flag.String("prefix", "gw", "Wallet ID / filename prefix")
	)
	flag.Parse()

	if *targetTotal <= 0 {
		log.Fatal("target-total must be > 0")
	}
	if *targetShard2 < 0 || *targetShard2 > *targetTotal {
		log.Fatal("target-shard2 must be between 0 and target-total")
	}
	if *activeShard2 < 0 || *reserveShard2 < 0 || *activeShard2+*reserveShard2 > *targetShard2 {
		log.Fatal("active-shard2 + reserve-shard2 cannot exceed target-shard2")
	}

	mf, err := manifest.LoadIfExists(*manifestPath)
	if err != nil {
		log.Fatalf("load manifest: %v", err)
	}
	if mf.Version == 0 {
		mf.Version = 1
	}

	if err := os.MkdirAll(*walletsDir, 0o755); err != nil {
		log.Fatalf("create wallets dir: %v", err)
	}

	existingIDs := make(map[string]struct{}, len(mf.Wallets))
	existingPaths := make(map[string]struct{}, len(mf.Wallets))
	totalCount := len(mf.Wallets)
	shard2Count := 0
	nextIndex := 1
	for _, w := range mf.Wallets {
		existingIDs[w.WalletID] = struct{}{}
		if w.PemPath != "" {
			existingPaths[filepath.Clean(w.PemPath)] = struct{}{}
		}
		if w.Shard == 2 {
			shard2Count++
		}
		if n, ok := parseSuffixNumber(w.WalletID, *prefix); ok && n >= nextIndex {
			nextIndex = n + 1
		}
	}

	added := 0
	for totalCount < *targetTotal || shard2Count < *targetShard2 {
		seed := make([]byte, ed25519.SeedSize)
		if _, err := rand.Read(seed); err != nil {
			log.Fatalf("generate seed: %v", err)
		}
		priv := ed25519.NewKeyFromSeed(seed)
		pub := priv.Public().(ed25519.PublicKey)

		address, err := wallets.PubKeyToBech32(pub)
		if err != nil {
			log.Fatalf("derive address: %v", err)
		}
		shard := wallets.ShardOfPubKey(pub)

		needShard2 := shard2Count < *targetShard2
		needMoreTotal := totalCount < *targetTotal
		if needShard2 && shard != 2 {
			continue
		}
		if !needMoreTotal && !needShard2 {
			break
		}

		walletID := fmt.Sprintf("%s-%03d", *prefix, nextIndex)
		nextIndex++
		for {
			if _, exists := existingIDs[walletID]; !exists {
				break
			}
			walletID = fmt.Sprintf("%s-%03d", *prefix, nextIndex)
			nextIndex++
		}

		pemFile := walletID + ".pem"
		pemDiskPath := filepath.Join(*walletsDir, pemFile)
		for {
			if _, exists := existingPaths[filepath.Clean(pemDiskPath)]; !exists {
				break
			}
			walletID = fmt.Sprintf("%s-%03d", *prefix, nextIndex)
			nextIndex++
			pemFile = walletID + ".pem"
			pemDiskPath = filepath.Join(*walletsDir, pemFile)
		}

		if err := writePem(seed, pemDiskPath); err != nil {
			log.Fatalf("write pem %s: %v", pemDiskPath, err)
		}

		record := manifest.WalletRecord{
			WalletID: walletID,
			Address:  address,
			Shard:    shard,
			PemFile:  pemFile,
			PemPath:  toSlashPath(pemDiskPath),
			Status:   "window_b_reserve",
			Tags:     []string{fmt.Sprintf("shard%d", shard), "sender"},
			Enabled:  true,
			Notes:    "Generated by cmd/genwallets.",
		}
		if shard == 2 {
			record.Tags = append(record.Tags, "window_a")
		} else {
			record.Tags = append(record.Tags, "window_b")
		}

		mf.Wallets = append(mf.Wallets, record)
		existingIDs[walletID] = struct{}{}
		existingPaths[filepath.Clean(pemDiskPath)] = struct{}{}
		totalCount++
		if shard == 2 {
			shard2Count++
		}
		added++
		if added%25 == 0 {
			log.Printf("generated=%d total=%d shard2=%d", added, totalCount, shard2Count)
		}
	}

	mf.GeneratedAt = time.Now().UTC().Format(time.RFC3339)
	assignStatuses(mf, *activeShard2, *reserveShard2)

	if err := mf.Validate(); err != nil {
		log.Fatalf("validate manifest: %v", err)
	}
	if err := mf.Save(*manifestPath); err != nil {
		log.Fatalf("save manifest: %v", err)
	}

	s := mf.Summary()
	log.Printf("saved manifest=%s wallets=%d enabled=%d shard2=%d added=%d", *manifestPath, len(mf.Wallets), s.TotalEnabled, s.ByShard[2], added)
}

func writePem(seed []byte, path string) error {
	body := []byte(hex.EncodeToString(seed))
	block := &pem.Block{
		Type:  "PRIVATE KEY",
		Bytes: body,
	}
	b := pem.EncodeToMemory(block)
	return os.WriteFile(path, b, 0o600)
}

func assignStatuses(mf *manifest.Manifest, activeShard2 int, reserveShard2 int) {
	activeUsed := 0
	reserveUsed := 0
	for i := range mf.Wallets {
		w := &mf.Wallets[i]
		if !w.Enabled {
			continue
		}
		if w.Status == "treasury" || w.Status == "receiver" {
			continue
		}

		w.Tags = normalizeTags(w.Tags, fmt.Sprintf("shard%d", w.Shard), "sender")
		if w.Shard == 2 {
			w.Tags = normalizeTags(w.Tags, "window_a")
			if activeUsed < activeShard2 {
				w.Status = "active_candidate"
				activeUsed++
				continue
			}
			if reserveUsed < reserveShard2 {
				w.Status = "warm_reserve"
				reserveUsed++
				continue
			}
			w.Status = "window_b_reserve"
			w.Tags = normalizeTags(w.Tags, "window_b")
			continue
		}

		w.Status = "window_b_reserve"
		w.Tags = normalizeTags(w.Tags, "window_b")
	}
}

func normalizeTags(tags []string, extra ...string) []string {
	seen := make(map[string]struct{}, len(tags)+len(extra))
	out := make([]string, 0, len(tags)+len(extra))
	for _, tag := range append(tags, extra...) {
		tag = strings.TrimSpace(tag)
		if tag == "" {
			continue
		}
		key := strings.ToLower(tag)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, tag)
	}
	return out
}

func parseSuffixNumber(id string, prefix string) (int, bool) {
	if !strings.HasPrefix(id, prefix+"-") {
		return 0, false
	}
	var n int
	_, err := fmt.Sscanf(id, prefix+"-%d", &n)
	if err != nil {
		return 0, false
	}
	return n, true
}

func toSlashPath(path string) string {
	return filepath.ToSlash(path)
}
