package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"encoding/pem"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"kwakbon/internal/manifest"
	"kwakbon/internal/wallets"
)

type genConfig struct {
	manifestPath string
	walletsDir   string
	prefix       string
	mode         string

	targetTotal   int
	targetShard2  int
	activeShard2  int
	reserveShard2 int

	targetShard0 int
	targetShard1 int
	targetShard2C3 int
	status      string
	extraTags   []string
	notes       string
}

func main() {
	var (
		cfg genConfig
		extraTagsRaw string
	)

	flag.StringVar(&cfg.manifestPath, "manifest", "./configs/wallets-manifest.json", "Path to wallets manifest JSON")
	flag.StringVar(&cfg.walletsDir, "wallets-dir", "./wallets", "Directory where PEM files are written")
	flag.StringVar(&cfg.prefix, "prefix", "gw", "Wallet ID / filename prefix")
	flag.StringVar(&cfg.mode, "mode", "legacy", "Generation mode: legacy or challenge3")

	flag.IntVar(&cfg.targetTotal, "target-total", 497, "Legacy mode: target total wallet count in manifest after generation")
	flag.IntVar(&cfg.targetShard2, "target-shard2", 250, "Legacy mode: target shard-2 wallet count in manifest after generation")
	flag.IntVar(&cfg.activeShard2, "active-shard2", 150, "Legacy mode: how many shard-2 wallets should be marked active_candidate")
	flag.IntVar(&cfg.reserveShard2, "reserve-shard2", 100, "Legacy mode: how many shard-2 wallets should be marked warm_reserve")

	flag.IntVar(&cfg.targetShard0, "target-shard0", 166, "Challenge3 mode: target shard-0 wallet count")
	flag.IntVar(&cfg.targetShard1, "target-shard1", 167, "Challenge3 mode: target shard-1 wallet count")
	flag.IntVar(&cfg.targetShard2C3, "target-shard2-c3", 167, "Challenge3 mode: target shard-2 wallet count")
	flag.StringVar(&cfg.status, "status", "challenge3_part1_sender", "Challenge3 mode: status assigned to generated wallets")
	flag.StringVar(&extraTagsRaw, "extra-tags", "sender,challenge3,part1", "Challenge3 mode: comma-separated tags applied to generated wallets")
	flag.StringVar(&cfg.notes, "notes", "Generated by cmd/genwallets for Challenge 3.", "Challenge3 mode: notes assigned to generated wallets")

	flag.Parse()

	cfg.mode = strings.ToLower(strings.TrimSpace(cfg.mode))
	cfg.extraTags = splitCSV(extraTagsRaw)

	switch cfg.mode {
	case "legacy":
		validateLegacyConfig(cfg)
	case "challenge3":
		validateChallenge3Config(cfg)
	default:
		log.Fatalf("unsupported mode %q (expected legacy or challenge3)", cfg.mode)
	}

	mf, err := manifest.LoadIfExists(cfg.manifestPath)
	if err != nil {
		log.Fatalf("load manifest: %v", err)
	}
	if mf.Version == 0 {
		mf.Version = 1
	}

	if err := os.MkdirAll(cfg.walletsDir, 0o755); err != nil {
		log.Fatalf("create wallets dir: %v", err)
	}

	state := buildState(mf, cfg.prefix)
	added := 0

	switch cfg.mode {
	case "legacy":
		added = generateLegacy(mf, state, cfg)
		assignLegacyStatuses(mf, cfg.activeShard2, cfg.reserveShard2)
	case "challenge3":
		added = generateChallenge3(mf, state, cfg)
	}

	mf.GeneratedAt = time.Now().UTC().Format(time.RFC3339)
	if err := mf.Validate(); err != nil {
		log.Fatalf("validate manifest: %v", err)
	}
	if err := mf.Save(cfg.manifestPath); err != nil {
		log.Fatalf("save manifest: %v", err)
	}

	s := mf.Summary()
	log.Printf(
		"saved manifest=%s wallets=%d enabled=%d shard0=%d shard1=%d shard2=%d added=%d",
		cfg.manifestPath,
		len(mf.Wallets),
		s.TotalEnabled,
		s.ByShard[0],
		s.ByShard[1],
		s.ByShard[2],
		added,
	)
}

type generationState struct {
	existingIDs   map[string]struct{}
	existingPaths map[string]struct{}
	nextIndex     int
	totalCount    int
	byShard       map[int]int
}

func buildState(mf *manifest.Manifest, prefix string) generationState {
	state := generationState{
		existingIDs:   make(map[string]struct{}, len(mf.Wallets)),
		existingPaths: make(map[string]struct{}, len(mf.Wallets)),
		nextIndex:     1,
		totalCount:    len(mf.Wallets),
		byShard:       map[int]int{0: 0, 1: 0, 2: 0},
	}

	for _, w := range mf.Wallets {
		state.existingIDs[w.WalletID] = struct{}{}
		if w.PemPath != "" {
			state.existingPaths[filepath.Clean(w.PemPath)] = struct{}{}
		}
		state.byShard[w.Shard]++
		if n, ok := parseSuffixNumber(w.WalletID, prefix); ok && n >= state.nextIndex {
			state.nextIndex = n + 1
		}
	}
	return state
}

func validateLegacyConfig(cfg genConfig) {
	if cfg.targetTotal <= 0 {
		log.Fatal("target-total must be > 0")
	}
	if cfg.targetShard2 < 0 || cfg.targetShard2 > cfg.targetTotal {
		log.Fatal("target-shard2 must be between 0 and target-total")
	}
	if cfg.activeShard2 < 0 || cfg.reserveShard2 < 0 || cfg.activeShard2+cfg.reserveShard2 > cfg.targetShard2 {
		log.Fatal("active-shard2 + reserve-shard2 cannot exceed target-shard2")
	}
}

func validateChallenge3Config(cfg genConfig) {
	if cfg.targetShard0 < 0 || cfg.targetShard1 < 0 || cfg.targetShard2C3 < 0 {
		log.Fatal("challenge3 shard targets must be >= 0")
	}
	if cfg.targetShard0+cfg.targetShard1+cfg.targetShard2C3 <= 0 {
		log.Fatal("challenge3 shard targets must sum to > 0")
	}
	if strings.TrimSpace(cfg.status) == "" {
		log.Fatal("challenge3 status must not be empty")
	}
	if len(cfg.extraTags) == 0 {
		log.Fatal("challenge3 extra-tags must include at least one tag")
	}
}

func generateLegacy(mf *manifest.Manifest, state generationState, cfg genConfig) int {
	added := 0
	for state.totalCount < cfg.targetTotal || state.byShard[2] < cfg.targetShard2 {
		record, ok := newWalletRecord(&state, cfg)
		if !ok {
			continue
		}
		needShard2 := state.byShard[2] < cfg.targetShard2
		needMoreTotal := state.totalCount < cfg.targetTotal
		if needShard2 && record.Shard != 2 {
			continue
		}
		if !needMoreTotal && !needShard2 {
			break
		}

		record.Status = "window_b_reserve"
		record.Tags = normalizeTags([]string{fmt.Sprintf("shard%d", record.Shard), "sender"})
		if record.Shard == 2 {
			record.Tags = normalizeTags(record.Tags, "window_a")
		} else {
			record.Tags = normalizeTags(record.Tags, "window_b")
		}
		record.Notes = "Generated by cmd/genwallets."

		appendRecord(mf, &state, record)
		added++
		if added%25 == 0 {
			log.Printf("generated=%d total=%d shard2=%d", added, state.totalCount, state.byShard[2])
		}
	}
	return added
}

func generateChallenge3(mf *manifest.Manifest, state generationState, cfg genConfig) int {
	added := 0
	targets := map[int]int{
		0: cfg.targetShard0,
		1: cfg.targetShard1,
		2: cfg.targetShard2C3,
	}

	for state.byShard[0] < targets[0] || state.byShard[1] < targets[1] || state.byShard[2] < targets[2] {
		record, ok := newWalletRecord(&state, cfg)
		if !ok {
			continue
		}
		if state.byShard[record.Shard] >= targets[record.Shard] {
			continue
		}

		record.Status = cfg.status
		record.Tags = normalizeTags(append([]string{fmt.Sprintf("shard%d", record.Shard)}, cfg.extraTags...))
		record.Notes = cfg.notes

		appendRecord(mf, &state, record)
		added++
		if added%25 == 0 {
			log.Printf(
				"generated=%d total=%d shard0=%d/%d shard1=%d/%d shard2=%d/%d",
				added,
				state.totalCount,
				state.byShard[0], targets[0],
				state.byShard[1], targets[1],
				state.byShard[2], targets[2],
			)
		}
	}
	return added
}

func newWalletRecord(state *generationState, cfg genConfig) (manifest.WalletRecord, bool) {
	seed := make([]byte, ed25519.SeedSize)
	if _, err := rand.Read(seed); err != nil {
		log.Fatalf("generate seed: %v", err)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)

	address, err := wallets.PubKeyToBech32(pub)
	if err != nil {
		log.Fatalf("derive address: %v", err)
	}
	shard := wallets.ShardOfPubKey(pub)

	walletID, pemFile, pemDiskPath := nextWalletPath(state, cfg.prefix, cfg.walletsDir)
	if err := writePem(seed, pemDiskPath); err != nil {
		log.Fatalf("write pem %s: %v", pemDiskPath, err)
	}

	return manifest.WalletRecord{
		WalletID: walletID,
		Address:  address,
		Shard:    shard,
		PemFile:  pemFile,
		PemPath:  toSlashPath(pemDiskPath),
		Enabled:  true,
	}, true
}

func appendRecord(mf *manifest.Manifest, state *generationState, record manifest.WalletRecord) {
	mf.Wallets = append(mf.Wallets, record)
	state.existingIDs[record.WalletID] = struct{}{}
	state.existingPaths[filepath.Clean(record.PemPath)] = struct{}{}
	state.totalCount++
	state.byShard[record.Shard]++
}

func nextWalletPath(state *generationState, prefix string, walletsDir string) (string, string, string) {
	nextIndex := state.nextIndex
	walletID := fmt.Sprintf("%s-%03d", prefix, nextIndex)
	nextIndex++
	for {
		if _, exists := state.existingIDs[walletID]; !exists {
			break
		}
		walletID = fmt.Sprintf("%s-%03d", prefix, nextIndex)
		nextIndex++
	}

	pemFile := walletID + ".pem"
	pemDiskPath := filepath.Join(walletsDir, pemFile)
	for {
		if _, exists := state.existingPaths[filepath.Clean(pemDiskPath)]; !exists {
			break
		}
		walletID = fmt.Sprintf("%s-%03d", prefix, nextIndex)
		nextIndex++
		pemFile = walletID + ".pem"
		pemDiskPath = filepath.Join(walletsDir, pemFile)
	}
	state.nextIndex = nextIndex
	return walletID, pemFile, pemDiskPath
}

func writePem(seed []byte, path string) error {
	body := []byte(hex.EncodeToString(seed))
	block := &pem.Block{
		Type:  "PRIVATE KEY",
		Bytes: body,
	}
	b := pem.EncodeToMemory(block)
	return os.WriteFile(path, b, 0o600)
}

func assignLegacyStatuses(mf *manifest.Manifest, activeShard2 int, reserveShard2 int) {
	activeUsed := 0
	reserveUsed := 0
	for i := range mf.Wallets {
		w := &mf.Wallets[i]
		if !w.Enabled {
			continue
		}
		if w.Status == "treasury" || w.Status == "receiver" {
			continue
		}

		w.Tags = normalizeTags(w.Tags, fmt.Sprintf("shard%d", w.Shard), "sender")
		if w.Shard == 2 {
			w.Tags = normalizeTags(w.Tags, "window_a")
			if activeUsed < activeShard2 {
				w.Status = "active_candidate"
				activeUsed++
				continue
			}
			if reserveUsed < reserveShard2 {
				w.Status = "warm_reserve"
				reserveUsed++
				continue
			}
			w.Status = "window_b_reserve"
			w.Tags = normalizeTags(w.Tags, "window_b")
			continue
		}

		w.Status = "window_b_reserve"
		w.Tags = normalizeTags(w.Tags, "window_b")
	}
}

func normalizeTags(tags []string, extra ...string) []string {
	seen := make(map[string]struct{}, len(tags)+len(extra))
	out := make([]string, 0, len(tags)+len(extra))
	for _, tag := range append(tags, extra...) {
		tag = strings.TrimSpace(tag)
		if tag == "" {
			continue
		}
		key := strings.ToLower(tag)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, tag)
	}
	return out
}

func parseSuffixNumber(id string, prefix string) (int, bool) {
	if !strings.HasPrefix(id, prefix+"-") {
		return 0, false
	}
	var n int
	_, err := fmt.Sscanf(id, prefix+"-%d", &n)
	if err != nil {
		return 0, false
	}
	return n, true
}

func toSlashPath(path string) string {
	return filepath.ToSlash(path)
}

func splitCSV(in string) []string {
	if strings.TrimSpace(in) == "" {
		return nil
	}
	parts := strings.Split(in, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		v := strings.TrimSpace(part)
		if v != "" {
			out = append(out, v)
		}
	}
	return out
}
